[digits]: code refactoring + implementing the `fa to ar` converter
persian-tools/persian-tools pull request #109
Opened 2021-08-31 20:14 UTC by psparsa

2021-09-01 21:56 UTC, ali-master requested changes

2021-09-01 21:56 UTC, ali-master commented on src/modules/digits/converters/strConverter.ts
> +const strConverter: StrConverter = ({ str, originCharList, destCharList }) =>
Rename this fn to ```digitsConverter```

2021-09-01 21:56 UTC, ali-master commented on src/modules/digits/converters/numsList.ts
> +const enNums = "0123456789".split("");
Replace with
```
const enNums = ["0", "1", "2", "3", "4" ...];
```
And do the same job for other variables.

2021-09-01 21:56 UTC, ali-master commented on src/modules/digits/converters/fa.ts
> +const digitsFaToAr: DigitsFaToX = (value) => {
```DigitsFaToX``` doesn't make any sense. please use the right Interface name instead like:

```ts
type DigitsConverter<T = string, R = string> = (value: T) => R;
```
`T` is the value type that can be dynamic and `R` is the result type which is dynamic too. This approach helps you to have a global type and use it everywhere you want such as:
```typescript
const digitsFaToAr: DigitsConverter = (value) => {
```
or for `digitsFaToEn`
```typescript
const digitsFaToEn: DigitsConverter<string, number> = (value) => {
```
or in `digitsEnToFa` case:
```typescript
const digitsEnToFa: DigitsConverter<number, string> = (value) => {
```

2021-09-01 21:56 UTC, ali-master commented on src/modules/digits/converters/fa.ts
> +const digitsFaToEn: DigitsFaToX = (value) => {
This function should return `number` instead of `string`

2021-09-01 21:56 UTC, ali-master commented on src/modules/digits/converters/ar.ts
> +const digitsArToEn: DigitsArToX = (value) => {
This function should return `number` instead of `string`

2021-09-02 01:01 UTC, psparsa commented on src/modules/digits/converters/fa.ts
> +const digitsFaToEn: DigitsFaToX = (value) => {
i don't think so, what will happen if we pass the `۰۰۱۰۱۱۰۱` (_which is a binary number_) to `digitsFaToEn`? the output will be unexpected.

e.g:

```
const num = 00101101;
console.log(num); //output: 33345
```

2021-09-02 13:08 UTC, ali-master commented on src/modules/digits/converters/fa.ts
> +const digitsFaToEn: DigitsFaToX = (value) => {
This function is not a binary converter.

2021-09-02 18:35 UTC, psparsa commented on src/modules/digits/converters/fa.ts
> +const digitsFaToEn: DigitsFaToX = (value) => {
i know, but it was just an example.. the value could be a number which contains arabic, farsi and english digits... and the `FaToEn` function only turns farsi numbers into english, what about the rest digits, the arabic one?

2021-09-02 21:24 UTC, ali-master requested changes

2021-09-02 21:24 UTC, ali-master commented on src/modules/digits/converters/ar.ts
> +const digitsArToFa: DigitsOrigToDest = (value) => {
What does `DigitsOrigToDest` mean?

2021-09-02 21:24 UTC, ali-master commented on src/modules/digits/converters/digitsConverter.ts
> +		.map((char) => {
The time complexity of this function is **o(n^2)** which is not a good idea for large texts, Regex is faster because is Running a DFA-compiled regular expression against a string is indeed **O(n)**, but can require up to **O(2^m)** construction time/space (where m = regular expression size).

2021-09-03 03:41 UTC, psparsa commented on src/modules/digits/converters/digitsConverter.ts
> +		.map((char) => {
that's O(n) (n = string.length), did you consider the language APIs ( `indexOf`)?

in the previous code, the regex was used but that looks tricky, hard to read and maintain ([also was slower](https://jsben.ch/Xe4Mm)). I know other ways to do this just by regex and replace method but still, there are few problems, such as creating abstraction for `digitsConverter`.

(fa to en):
string.replace(/[۰۱۲۳۴۵۶۷۸۹]/g, (char) =>  "۰۱۲۳۴۵۶۷۸۹".indexOf(char));

(fa to ar):
string.replace(/[۰۱۲۳۴۵۶۷۸۹]/g, (char) => "۰۱۲۳٤٥٦۷۸۹"["۰۱۲۳۴۵۶۷۸۹".indexOf(char)])

i think at this point/level readability and simplicity are more important than performance; for example, if we pass a long string (with 1,000,000 characters) to this function it takes less than 1 second!
do we really need to save 0.10 or 0.20 seconds?

2021-09-03 14:01 UTC, ali-master commented on src/modules/digits/converters/digitsConverter.ts
> +		.map((char) => {
Check this [benchmark](https://jsben.ch/KnTL5) out.

2021-09-04 11:05 UTC, ali-master commented
https://github.com/persian-tools/persian-tools/issues/103

May you take a look at this issue and fix that?

2021-09-04 11:09 UTC, ali-master requested changes

2021-09-04 11:09 UTC, ali-master commented on src/types/DigitsConverter.d.ts
> +declare type DigitsConverter<I = string, O = string> = (value: I) => O;
Please prevent creating a Global typescript file(Developers should be able to import the `type` if they want) and your types file/folder should be alongside your functions.

2021-09-04 18:06 UTC, psparsa commented
> #103
> 
> May you take a look at this issue and fix that?

i fixed that in the last commits... i will write some new test for such cases.

2021-09-04 19:18 UTC, ali-master requested changes

2021-09-04 19:18 UTC, ali-master commented on src/modules/digits/converters/DigitsConverterType.ts
> +export default DigitsConverter;
Please prevent using `export default` and just use the `export`statement, because we should import it with the same name as you exported.

2021-09-05 10:26 UTC, merged