feat: add phone number normalizer
persian-tools/persian-tools pull request #184
Opened 2022-05-03 16:19 UTC by mediv0

Discussed here https://github.com/persian-tools/persian-tools/discussions/183

tests & docs included

2022-05-03 16:34 UTC, mediv0 commented
should i make pull request to develop branch ?
my local repo is based of master need to rebase

2022-05-03 16:43 UTC, ghost commented
### CodeSee Review Map:
[![Review these changes using an interactive CodeSee Map](https://s3.us-east-2.amazonaws.com/maps.codesee.io/images/github/persian-tools/persian-tools/184/e66896e6/65e9d1f4d5e25b7a56ab809099f6e6b5abfe7316.svg)](https://app.codesee.io/r/reviews?pr=184&src=https%3A%2F%2Fgithub.com%2Fpersian-tools%2Fpersian-tools)

Review [in an interactive map](https://app.codesee.io/r/reviews?pr=184&src=https%3A%2F%2Fgithub.com%2Fpersian-tools%2Fpersian-tools)

View [more CodeSee Maps](https://app.codesee.io/r/maps?src=https%3A%2F%2Fgithub.com%2Fpersian-tools%2Fpersian-tools)

#### Legend
![CodeSee Map Legend](https://app.codesee.io/Legend_v2.png)

2022-05-04 11:02 UTC, ali-master commented on README.md
> +phoneNumberNormalizer("+989022002580", "0"); // 09022002580
OMG, My personal phone number is everywhere ^_^

2022-05-04 11:03 UTC, ali-master commented on README.md
> +phoneNumberNormalizer("09802002580", "0"); // Error: phone number is not valid
Please remove this sample because there is no need to write error base examples in README.

2022-05-04 11:05 UTC, ali-master requested changes
Ready to Merge after fixing an issue.

2022-05-06 16:40 UTC, merged

2022-05-06 16:40 UTC, ali-master commented
Thanks @mediv0 Jan.