feat: add new module
persian-tools/persian-tools pull request #223
Opened 2022-07-03 19:58 UTC by Amirali-Yavari

با سلام 
تابعی که به عنوان ورودی اسم استان را بگیرد و در خروجی مرکز استان را برگرداند
```
findCapitalByStateName('خراسان رضوی')

return: 'مشهد'
```

2022-07-03 20:10 UTC, mediv0 commented
test files ?

2022-07-03 20:46 UTC, Amirali-Yavari commented
in progress

2022-07-04 21:33 UTC, Amirali-Yavari commented
Test file commited

2022-07-05 09:45 UTC, mediv0 commented
لطفا تغییراتی که بالاتر گفتم رو بررسی کن
فایل ها باید تایپ اسکریپت باشه و تایپینگ و... رعایت شده باشه
ماژول رو داخل `index.ts` اکسپورت بشه
توضیحات و نحوه استفاده هم داخل `README.MD` اضافه کن
همچنین ماژولی که نوشتی باید JSDOC هم داشته باشه

2022-07-07 17:34 UTC, Amirali-Yavari commented
درخواست ها انجام شد

2022-07-07 19:14 UTC, mediv0 commented
> 

ممنون. خسته نباشی

اما درخواست اصلی هنوز انجام نشده. لطفا اسکرول کن بالا تر 3 تا ریویو هنوز pending هست

2022-07-07 21:03 UTC, ali-master requested changes

2022-07-07 21:03 UTC, ali-master commented on test/findCapitalByStateName.spec.ts
>  it("findCapitalByStateName", () => {
I've migrated all tests to vitest from jest, so please update your infra.

2022-07-07 21:07 UTC, ali-master commented
امیرعلی جان، لطفا اسم تابع رو به`findCapitalByProvince` تغییر بده که معنی مفهوم تابع رو برسونه.

2022-07-11 18:16 UTC, Amirali-Yavari commented
تغییرات انجام شد با تاخیر ☺️

2022-07-11 21:54 UTC, Amirali-Yavari commented
فایل تست رو تغییرات دادم ولی با ارور 
` No files matching the pattern were found: "'src/**/*.{ts,json}'".
husky - pre-commit hook exited with code 2 (error)`
برخورد میکنم موقع کامیت کردن

2022-07-17 22:33 UTC, Amirali-Yavari commented
سلام دوستان عزیز تغییرات انجام شد

2022-07-19 06:32 UTC, ali-master requested changes

2022-07-19 06:32 UTC, ali-master commented on README.md
> +> finding capital city name of state you enter
change to:
```
This function returns the Capital City name by its state name but if the State name was the Capital name, it produces a string with the value: `self`. if the function can't find anything, it throws an error.
```

2022-07-19 06:32 UTC, ali-master commented on src/modules/findCapitalByProvince/index.ts
> +  return '404'
Throw an error. String `404` doesn't make any sense.

2022-07-19 06:32 UTC, ali-master commented on src/modules/findCapitalByProvince/index.ts
> +  return '404'
use `for in` syntax.

2022-07-19 06:35 UTC, ali-master commented
چندتا مشکلی که وجود داره اینه که لطفا توی کد برطرفشون کن:
-  اگر حروف عربی توی ورودی باشه تابع دیگه درست کار نمیکنه
-  اگر بجای فاصله، نیم فاصله استفاده بشه بازم تابع کار نمیکنه
-  این تابع درصورتی که چیزی پیدا نکنه باید خطا برگردونه و خطاش رو هم توی مستند باید نوشته بشه
- توی فایل README، اول فایل یک لیستی از فیچر ست ها وجود داره که آیدی section ای که داری بابت این تابع رو باید اونجا هم با عنوانش درج کنی.

2022-07-19 20:10 UTC, Amirali-Yavari commented
خسته نباشی علی جان مشکلات مطرح شده برطرف شد 🚀

2022-08-04 18:24 UTC, Amirali-Yavari commented
سلام علی جان لطفا review رو انجام بدید

2022-08-30 22:04 UTC, Amirali-Yavari reviewed
Fixed

2022-08-30 22:08 UTC, Amirali-Yavari commented
> چندتا مشکلی که وجود داره اینه که لطفا توی کد برطرفشون کن:
> 
> * اگر حروف عربی توی ورودی باشه تابع دیگه درست کار نمیکنه
> * اگر بجای فاصله، نیم فاصله استفاده بشه بازم تابع کار نمیکنه
> * این تابع درصورتی که چیزی پیدا نکنه باید خطا برگردونه و خطاش رو هم توی مستند باید نوشته بشه
> * توی فایل README، اول فایل یک لیستی از فیچر ست ها وجود داره که آیدی section ای که داری بابت این تابع رو باید اونجا هم با عنوانش درج کنی.

@ali-master 
این قسمت انجام شده

2022-08-31 00:47 UTC, mediv0 commented
> سلام علی جان لطفا review رو انجام بدید
> 
> @ali-master @mediv0

سلام بالاتر یه سری کامنت هست توضیح دادم کجا میتونه بهتر باشه و خوبه که تغییر کنه. اینجا دوباره نمینویسم. اگر سوالی بود بپرس سعی میکنم جواب بدم 
نکنه مهم اینکه خوانایی و مرتبه زمانی کد خیلی میتونه بهتر از این چیزی که در حال حاضر هست، باشه

2023-07-30 17:14 UTC, merged