feat(digits) add error handling and cleanup
persian-tools/persian-tools pull request #62
Opened 2021-03-20 11:43 UTC by masoudDaliriyan

2021-03-20 16:20 UTC, ali-master commented on src/modules/digits/index.ts
> +		// @ts-ignore
Remove `@ts-ignore` and fix the issue

2021-03-20 16:20 UTC, ali-master commented on src/modules/digits/index.ts
>   */
Please update the functions' JSDocs

2021-03-20 16:27 UTC, ali-master requested changes
Reviewed

2021-03-20 16:27 UTC, ali-master commented on src/helpers/index.ts
> +export function isString(value: string): boolean {
There is no related tests for `isString` and `isNumber` functions.

2021-03-20 16:27 UTC, ali-master commented on src/helpers/index.ts
> +	return {}.toString.call(value) === "[object String]";
Please create a function:
```js
function getType(value: any): string {
   return Object.prototype.toString.call(value).slice(8, -1).toLowerCase();
}
```
And then use this function in `isString` or `isNumber` functions as below:
```js
function isNumber(value: any): boolean {
    return getType(value) === "number";
}
```

2021-03-23 22:16 UTC, ali-master commented
Hi @masoudDaliriyan Jan,

Can you complete the PR and make it ready for merge?

2021-03-24 08:00 UTC, masoudDaliriyan commented
Hi @ali-master
I'm working on that to night

2021-07-08 14:51 UTC, closed without merging