approaching to the functional paradigm (`numberToWords`) + handle the largest possible number (`2^53 - 1`)
persian-tools/persian-tools pull request #84
Opened 2021-06-01 20:36 UTC by psparsa

2021-06-02 09:09 UTC, ali-master commented on src/modules/numberToWords/index.ts
> +	const notValidNumberError = () => TypeError("the number must be a safe integer value");
TypeError message should follow the PersianTools errors rule while you can see in some other files we've added before.

2021-06-02 09:24 UTC, ali-master commented on src/modules/numberToWords/index.ts
> +	const notValidNumberError = () => TypeError("the number must be a safe integer value");
`notValidNumberError` should be `numberIsNotValidError`.

I prefer to create a Class and add all our Errors in one class which helps us to be regular.

2021-06-02 09:48 UTC, ali-master commented on test/NumberToWords.spec.ts
> +	expect(numberToWords(9006199254740992)).toEqual(
Add more tests and also update the README to inform users that this function supports large numbers.

2021-06-02 09:50 UTC, ali-master commented on src/modules/numberToWords/numbersWordList.ts
> +const numbersWordList: Map<number, string> = new Map([
Please check the browser compatibility after adding this function to ensure that the bundle works well in old nodejs and browsers version.

2021-06-02 09:50 UTC, ali-master commented on src/modules/numberToWords/index.ts
> +		if (Number(inputNumber) === 0) return "صفر";
Seems your code is not prettified.

2021-06-02 09:54 UTC, ali-master commented on src/modules/numberToWords/index.ts
> +		if (Number(inputNumber) === 0) return "صفر";
The `inputNumber` is a wrong variable name. it should `numberValue` or something like that.

2021-06-02 09:56 UTC, ali-master commented on src/modules/numberToWords/index.ts
> +	function performer(num: number) {
What is this function? what does it do? Write document above the function and also add return type.

2021-06-02 10:00 UTC, ali-master commented
Thanks for contributing to the Project and I appreciate it.

All your codes and lines should be documented and covered in the tests and please write more and more and more tests. one test is not enough. There are a lot of users who are using our project and we have to be very cautious about every single line of our codes.

2021-06-02 10:01 UTC, ali-master requested changes
I reviewed and there are some issues.

2021-06-02 11:49 UTC, psparsa commented
thanks for the review, I will fix these issues as soon as possible.

2021-06-22 14:30 UTC, psparsa commented
There is a bunch of failed tests that are not related to that part I am working on, so I can't/should not commit...
I neglect those?

2021-06-22 17:44 UTC, ali-master commented
> There is a bunch of failed tests that are not related to that part I am working on, so I can't/should not commit...
> should I neglect those?

I know, you should write at least 10 more tests to make sure that your changes have no backward compatibility side effects in production.

We want to release a new version, so please complete your PR as soon as possible.

2021-06-25 23:33 UTC, psparsa commented
the issues were resolved completely... BTW sorry for the delay.

2021-06-28 04:42 UTC, merged

2021-06-28 04:45 UTC, ali-master commented
@all-contributors please add @psparsa for tests, code and ideas

2021-06-28 05:00 UTC, ali-master commented
@psparsa Welcome to the PersianTools family. We are glad that you are a member of our family.